export const STATUS_AGENDAMENTO = [
  { label: 'Agendado', value: 1 },
  { label: 'Confirmado', value: 2 },
  { label: 'Finalizado', value: 3 },
  { label: 'Faltou', value: 4 },
  { label: 'Cancelado', value: 5 }
];

export const FACES_DO_DENTE = [
  { label: 'O', value: 1 },
  { label: 'L', value: 2 },
  { label: 'M', value: 3 },
  { label: 'V', value: 4 },
  { label: 'D', value: 5 },
  { label: 'I', value: 6 },
  { label: 'P', value: 7 },
  { label: 'MO', value: 8 },
  { label: 'DO', value: 9 },
  { label: 'MV', value: 10 },
  { label: 'DV', value: 11 },
  { label: 'OV', value: 12 },
  { label: 'ML', value: 13 },
  { label: 'MP', value: 14 },
  { label: 'DL', value: 15 },
  { label: 'DP', value: 16 },
  { label: 'OL', value: 17 },
  { label: 'OP', value: 18 },
  { label: 'MI', value: 19 },
  { label: 'DI', value: 20 },
  { label: 'MOD', value: 21 },
  { label: 'MVD', value: 22 },
  { label: 'MOV', value: 23 },
  { label: 'DOV', value: 24 },
  { label: 'MLD', value: 25 },
  { label: 'MPD', value: 26 },
  { label: 'MOL', value: 27 },
  { label: 'MOP', value: 28 },
  { label: 'DOL', value: 29 },
  { label: 'DOP', value: 30 },
  { label: 'VML', value: 31 },
  { label: 'WMP', value: 32 },
  { label: 'VDL', value: 33 },
  { label: 'VDP', value: 34 },
  { label: 'VOL', value: 35 },
  { label: 'VOP', value: 36 },
  { label: 'MID', value: 37 },
  { label: 'MODV', value: 38 },
  { label: 'MODL', value: 39 },
  { label: 'MODP', value: 40 },
  { label: 'VMDL', value: 41 },
  { label: 'VMDP', value: 42 },
  { label: 'MOVL', value: 43 },
  { label: 'MOVP', value: 44 },
  { label: 'DOVL', value: 45 },
  { label: 'DOVP', value: 46 },
  { label: 'MODVL', value: 47 },
  { label: 'MODVP', value: 48 },
];
